module.exports = {
  token: process.env.TOKEN || "OTkxOTQ5OTUzNjg3NjI1Nzgw.GJeN_1.ScqwDeoBI-6bISeFLzT2I2UDqdfEBHG8AAPc_k",
  prefix: process.env.PREFIX || "/",
  embed: {
    color: "#2f3136",
    wrongcolor: "#2f3136",
    footertext: "Coded in the Shadows | TSC BUIDL",
    footericon:
      "https://raw.githubusercontent.com/flipthetip/test-tsc/main/tase1%20(1).png?width=424&height=424",
  },
  emoji: {
    ERROR: "❌",
    SUCCESS: "✅",
    disabled: "🔴",
    enabled: "🟢",
    playing: "🎵",
    pruning: "📋",
    equalizer: "👀",
    cleared: "🧹",
    leave_on_empty: "🗣️",
    time: "⏲️",
    premium: "💰",
    song_by: "🗣️",
    dj: "🎧",
    search: "🔎",
    resume: "▶",
    pause: "⏸",
    lyrics: "📃",
    disk: "📀",
    ping: "🏓",
    rewind: "⏪",
    forward: "⏩",
    pause_resume: "⏯️",
    stop: "⏹️",
    previous_track: "⏮️",
    skip_track: "⏭️",
    replay_track: "🔃",
    reduce_volume: "🔉",
    raise_volume: "🔊",
    toggle_mute: "🔇",
    repeat_mode: "🔄",
    autoplay_mode: "♾",
    shuffle: "🔀",
    show_queue: "📑",
    show_current_track: "🩸",
    bot: "🤖",
  },
};
